# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    xteamuser.form.registration:
        class: XTeam\PlatformBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: xteam_user_registration }
