x_team_platform_utilisateur:
        resource: "@XTeamPlatformBundle/Resources/config/routing/utilisateur.yml"
        prefix:   /utilisateur

xteam_platform_accueil:
    path:     /
    defaults: { _controller: XTeamPlatformBundle:Main:index }
