XTeam\PlatformBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        profession:
            type: string
            length: 255
            nullable: true
        business:
            type: string
            length: 255
            nullable: true
        statut:
            type: string
            length: 255
        promo:
            type: string
            length: 255
            nullable: true
        git:
            type: string
            length: 255
        twitter:
            type: string
            length: 255
            nullable: true
        facebook:
            type: string
            length: 255
            nullable: true
        linkedin:
            type: string
            length: 255
        avatar:
            type: string
            length: 255
    lifecycleCallbacks: {  }
